feat: refactor readme, add test instructions
Mint-System/Odoo-Apps-Sale-Workflow pull request #21
Opened 2024-07-02 14:07 UTC by laszlokr

ValidationError needs investigation

```
The operation cannot be completed:
- Create/update: a mandatory field is not set.
- Delete: another model requires the record being deleted. If possible, archive it instead.

Model: Sales Order (sale.order)
Field: Invoice Address (partner_invoice_id)
```

2024-07-04 08:44 UTC, laszlokr commented
@janikvonrotz this module only copies the notes content from the quotation template, but not the actual order lines and other info. Is it required, or the purpose of the module is to only copy the notes from the template?

2024-07-05 06:40 UTC, janikvonrotz requested changes
Write inverse function for sale_order_template_id.

`inverse="_inverse_sale_order_template_id"`

2024-07-05 08:00 UTC, janikvonrotz requested changes

2024-07-05 08:00 UTC, janikvonrotz commented on sale_blanket_order_template/models/blanket_order.py
> +    def _inverse_sale_order_template_id(self):
Keep only the inverse method.

Check if it works without the compute method.

2024-07-08 06:53 UTC, janikvonrotz approved these changes

2024-07-26 06:09 UTC, merged