Mig16.0 sale order line date propagate
Mint-System/Odoo-Apps-Sale-Workflow pull request #26
Opened 2024-07-03 14:55 UTC by laszlokr

2024-07-04 06:07 UTC, janikvonrotz requested changes

2024-07-04 06:07 UTC, janikvonrotz commented on sale_order_line_date_propagate/tests/TEST_INSTRUCTIONS.rst
Odoo calls it "sale order" instead of "Sales Order".

2024-07-04 08:25 UTC, laszlokr commented on sale_order_line_date_propagate/tests/TEST_INSTRUCTIONS.rst
@janikvonrotz Sales Order would be a normal way to call it in English, if you type this in the Odoo search/launcher, I think it is spelled exactly like this in the UI elements (menus). I capitalize for things like Sales Order, Purchase Order, Blanket Order, Quotation Template, etc. because it is referring to a particular part in the UI that an action is applied to. 

In cases where it's not related to an action a test instruction applies, but to an abstract notion of a sale or purchase order, I just write it lowercase. I feel what you are referring to how Odoo calls it is the model naming conventions in the contributor guidelines: "When defining an Odoo Model : use singular form of the name (res.partner and sale.order instead of res.partnerS and saleS.orderS)". 

In any case, if you want to see it written as "sale order",  then it probably needs to be changed for all other test instruction where it is already written as "Sales Order".

2024-07-08 07:05 UTC, janikvonrotz requested changes

2024-07-08 07:05 UTC, janikvonrotz commented on sale_order_line_date_propagate/models/sale_order.py
Something seems odd. Why is it `_inherit = "sale.order.line"`?

2024-07-08 09:51 UTC, laszlokr commented on sale_order_line_date_propagate/models/sale_order.py
Something got mixed up there, I fixed it and also updated test instructions

2024-07-09 14:25 UTC, janikvonrotz approved these changes

2024-07-09 15:46 UTC, merged